#Minecraft server properties
#Sat Jun 06 16:27:26 UTC 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=easy
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=easyshulkerboxes\:map,lootr\:lootr_no_suspicious_blocks,easyshulkerboxes\:containers,easyshulkerboxes\:mod_support,lootr\:lootr_no_advancements
initial-enabled-packs=vanilla,advancednetherite,backpacked,balm,barteringstation,biomesoplenty,carryon,collective,comforts,ctov,diagonalblocks,easyanvils,easyshulkerboxes,elevatorid,elytratrims,eternalnether,explorerscompass,explorify,fabric-convention-tags-v2,fastitemframes,goblintraders,illagerinvasion,improved_village_placement,justhammers,kleeslabs,lithostitched,lootintegrations,lootr,mcwbiomesoplenty,mcwbridges,mcwdoors,mcwfences,mcwfurnitures,mcwholidays,mcwlights,mcwpaintings,mcwpaths,mcwroofs,mcwstairs,mcwtrpdoors,mcwwindows,medieval_buildings,medieval_nether,medievalend,mr_true_ending,mutantmonsters,naturescompass,rightclickharvest,sereneseasons,t_and_t,takesapillage,terrablender,throwable_spear,toms_storage,tradingpost,universalbonemeal,visualworkbench,waddles,waystones,easyshulkerboxes\:ender_chest,easyshulkerboxes\:shulker_boxes,easyshulkerboxes\:bundles,t_and_t\:resources/t_and_t_waystones_patch
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=B00LXtdEnnETrCI1tdkwHuEwgqdDQkqaoXkbkJJ9
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=§r              §5§l(MSX)  §dHosting Gratuito§r\n          §f§nhttps\://discord.gg/w9xt8ydNZe
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
